# T-2814 (Curie) -- the consumed-symbol generator of plan Sec3.7 item 3 (TE-266 GPU-path plan, D-SLM7313).
#
# Writes consumed_symbols.txt: the sorted, de-duplicated decorated names of every SuperSLM engine symbol
# that a sibling consumer's compiled objects import, one per line, headed by a comment naming each
# consumer, its commit and the objects read. The consumers' objects are the source of truth; the list is
# never typed by hand. X2 (build_x2.ps1) requires the engine DLL's export table and the X2 consumer's import
# table to EQUAL this list.
#
# A name is kept when `dumpbin /symbols` shows it UNDEF and External in a consumer object, and it matches
# `@superslm@@` (a C++ name in namespace superslm) or `^sslm_` (a C verb) CASE-SENSITIVELY (-cmatch).
# PowerShell's -match is case-insensitive and also admits a consumer's own `SuperSLM::` facade
# (`?...@SuperSLM@@`), which is not an engine symbol; that is the error the plan's derivation made once.
#
# Usage:
#   gen_consumed_symbols.ps1 -Consumer '<label>|<commit>|<objdir>[|<objdir>...]', '<second consumer>'
#                            [-Exclude 'SuperSLMVendored_*'] [-Out consumed_symbols.txt]
#   (-Consumer takes a comma-separated array; PowerShell rejects the flag given twice.)
#   Each <objdir> is searched recursively for *.obj. -Exclude drops objects whose file name matches a
#   wildcard: a consumer that compiles the engine's own sources into its module (SuperSLMUnreal's
#   vendored SuperSLMVendored_*.cpp) must exclude them, or engine-internal references are admitted.
#
# The release invocation (plan Sec3.5 step 5), with this ticket's inputs:
#   gen_consumed_symbols.ps1 `
#     -Consumer 'SuperEmbedder library|brunel/te265-slice7-build@d3321e5|D:\SuperEmbedder\.worktrees\te264-slice7-red\build\msvc\CMakeFiles\superembedder.dir', `
#               'SuperSLMUnreal modules|develop@<sha>|<Plugin>\Intermediate\Build\Win64\x64\UnrealEditor\Development\SuperSLMUnreal|...\SuperSLMUnrealEditor|...\SuperSLMUnrealTests'
#
# -Recorded '<label>|<commit>|<tsv>' takes a consumer from an earlier per-object dumpbin read instead of
# live objects: a TSV whose LAST column is an imported name and whose second-to-last is the object it
# came from (Claude/Vitruvius/t2807-probe/imports-*.tsv). The same case-sensitive filter is applied to it.
# Use it only when the consumer's objects at the named commit no longer exist on disk; the header records
# which inputs were recorded rather than live.
param(
    [string[]]$Consumer = @(),
    [string[]]$Recorded = @(),
    [string[]]$Exclude = @('SuperSLMVendored_*'),
    [string]$Out = (Join-Path $PSScriptRoot 'consumed_symbols.txt')
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'vsenv.ps1')

$union = New-Object 'System.Collections.Generic.SortedSet[string]' ([System.StringComparer]::Ordinal)
$header = @(
    '# SuperSLM engine symbols consumed across a shared-library boundary by sibling UE modules.',
    '# GENERATED by tests/t2807-api-slot/gen_consumed_symbols.ps1 -- do not edit by hand. Plan: TE-266 Sec3.7.',
    '# Filter: dumpbin /symbols, UNDEF External, -cmatch ''@superslm@@'' or ''^sslm_''.'
)
foreach ($spec in $Consumer) {
    $parts = $spec -split '\|'
    if ($parts.Count -lt 3) { throw "bad -Consumer '$spec' (want <label>|<commit>|<objdir>[|<objdir>...])" }
    $label = $parts[0]; $commit = $parts[1]; $dirs = $parts[2..($parts.Count - 1)]
    $objs = foreach ($d in $dirs) {
        if (-not (Test-Path $d)) { throw "object directory not found: $d" }
        Get-ChildItem -Path $d -Recurse -Filter *.obj -File |
            Where-Object { $n = $_.Name; -not ($Exclude | Where-Object { $n -like $_ }) }
    }
    $objs = @($objs | Sort-Object FullName)
    if ($objs.Count -eq 0) { throw "no objects for consumer '$label'" }
    $mine = New-Object 'System.Collections.Generic.SortedSet[string]' ([System.StringComparer]::Ordinal)
    foreach ($o in $objs) {
        $lines = & dumpbin.exe /nologo /symbols $o.FullName
        if ($LASTEXITCODE -ne 0) { throw "dumpbin failed on $($o.FullName)" }
        foreach ($l in $lines) {
            if ($l -cmatch '\bUNDEF\b.*\bExternal\s+\|\s+(\S+)') {
                $name = $Matches[1]
                if ($name -cmatch '@superslm@@' -or $name -cmatch '^sslm_') { [void]$mine.Add($name) }
            }
        }
    }
    $newest = ($objs | Sort-Object LastWriteTime | Select-Object -Last 1).LastWriteTime.ToString('yyyy-MM-dd HH:mm')
    $oldest = ($objs | Sort-Object LastWriteTime | Select-Object -First 1).LastWriteTime.ToString('yyyy-MM-dd HH:mm')
    $header += "# consumer: $label @ $commit -- $($objs.Count) objects (written $oldest .. $newest), $($mine.Count) engine symbols"
    foreach ($d in $dirs) { $header += "#   objects: $d (excluding $($Exclude -join ', '))" }
    foreach ($n in $mine) { [void]$union.Add($n) }
}
foreach ($spec in $Recorded) {
    $parts = $spec -split '\|'
    if ($parts.Count -ne 3) { throw "bad -Recorded '$spec' (want <label>|<commit>|<tsv>)" }
    $label = $parts[0]; $commit = $parts[1]; $tsv = $parts[2]
    if (-not (Test-Path $tsv)) { throw "recorded TSV not found: $tsv" }
    $mine = New-Object 'System.Collections.Generic.SortedSet[string]' ([System.StringComparer]::Ordinal)
    $objs = New-Object 'System.Collections.Generic.HashSet[string]'
    $rows = 0; $dropped = 0
    foreach ($l in (Get-Content $tsv)) {
        $f = $l -split "`t"
        if ($f.Count -lt 2) { continue }
        $rows++
        $name = $f[-1]
        if ($name -cmatch '@superslm@@' -or $name -cmatch '^sslm_') { [void]$mine.Add($name); [void]$objs.Add($f[-2]) }
        else { $dropped++ }
    }
    $sha = (Get-FileHash -Algorithm SHA256 $tsv).Hash.ToLower()
    $header += "# consumer: $label @ $commit -- RECORDED per-object dumpbin read $tsv (sha256 $sha): $rows rows, $($objs.Count) importing objects, $($mine.Count) engine symbols, $dropped rows dropped by the case-sensitive filter"
    foreach ($n in $mine) { [void]$union.Add($n) }
}
if ($Consumer.Count + $Recorded.Count -eq 0) { throw 'give at least one -Consumer or -Recorded' }
$header += "# union: $($union.Count) symbols"
$body = @($union)
[System.IO.File]::WriteAllLines($Out, [string[]]($header + $body))
Write-Output "wrote $Out : $($union.Count) symbols"
