"""T-2790 spike: generate the row-widened variant of every non-GEMM composed-pipeline site shader.

Each generated shader is the shipped shader with exactly four mechanical edits, so its arithmetic is
the shipped arithmetic, byte for byte in the source:

1. The three per-row buffers (SeqState u0, LayerScratch u1, WorkScratch u3) become arrays of
   SSLM_WIDE_H raw views, one per row (register spaces 1, 2, 3). KvCache (u2) stays one shared
   buffer: every row writes only its own position and reads positions 0..its own.
2. A thread-private `g_row` is declared, and `SeqState`/`LayerScratch`/`WorkScratch` become macros
   for the row's own view, so every existing Load/Store and every helper-call argument addresses
   the row's own window at the same offsets the per-token shader uses.
3. `g_position` and `g_width` become the row's own values: the host passes row 0's position and
   width, and row r is r positions later (`(g_position + g_row)`, `(g_width + g_row)`).
4. `main` takes SV_GroupID (added when absent) and sets `g_row = gid.y` first: the host dispatches
   (groups_x, SSLM_WIDE_H, 1), so group row y is sequence row y and SV_GroupID.x /
   SV_DispatchThreadID.x are exactly the per-token values.

The six GEMM sites are not generated: they are hand-written (`*_gemm_wide.hlsl`), because
amortising the weight stream needs one weight load serving every row, not one dispatch row per row.

Usage: python gen_wide_shaders.py   (reads ../shaders/<site>.hlsl, writes ./<site>_wide.hlsl)
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "shaders"

SITES = [
    "attn_norm_site", "q_proj_site", "kv_proj_site", "qk_norm_site", "rope_guard_site",
    "rope_commit_site", "attention_score_site", "softmax_site", "context_accumulate_site",
    "ctx_fold_site", "o_proj_site", "attn_residual_site", "mlp_norm_site", "gate_proj_site",
    "up_proj_site", "mlp_act_site", "down_proj_site", "mlp_residual_site", "commit_site",
]

SPACE = {"SeqState": 1, "LayerScratch": 2, "WorkScratch": 3}
DECL = re.compile(r"RWByteAddressBuffer\s+(SeqState|LayerScratch|WorkScratch)\s*:\s*register\(u[013]\)\s*;")
MAIN = re.compile(r"void\s+main\s*\(([^)]*)\)")


def widen(name: str, text: str) -> str:
    found = DECL.findall(text)
    if sorted(found) != sorted(SPACE):
        raise SystemExit(f"{name}: expected one declaration each of {sorted(SPACE)}, found {found}")
    text = DECL.sub(
        lambda m: f"RWByteAddressBuffer {m.group(1)}Rows[SSLM_WIDE_H] : register(u0, space{SPACE[m.group(1)]});",
        text)

    # Insert the row machinery after the line that carries the last of the three declarations.
    lines = text.split("\n")
    last = max(i for i, ln in enumerate(lines) if re.search(r"(SeqState|LayerScratch|WorkScratch)Rows\[", ln))
    block = [
        "// T-2790 spike (generated): row machinery -- see gen_wide_shaders.py.",
        "static uint g_row;",
        "#define SeqState SeqStateRows[g_row]",
        "#define LayerScratch LayerScratchRows[g_row]",
        "#define WorkScratch WorkScratchRows[g_row]",
        "#define g_position (g_position + g_row)",
        "#define g_width (g_width + g_row)",
    ]
    lines[last + 1:last + 1] = block
    text = "\n".join(lines)

    m = MAIN.search(text)
    if not m:
        raise SystemExit(f"{name}: no main")
    params = m.group(1)
    gid = re.search(r"uint3\s+(\w+)\s*:\s*SV_GroupID\b", params)
    if gid:
        gid_name = gid.group(1)
        new_params = params
    else:
        gid_name = "sslm_wide_gid"
        new_params = params + ", uint3 sslm_wide_gid : SV_GroupID"
    text = text[:m.start(1)] + new_params + text[m.end(1):]
    brace = text.index("{", m.start())
    text = text[:brace + 1] + f"\n    g_row = {gid_name}.y;  // T-2790 spike: dispatch row y is sequence row y" + text[brace + 1:]

    header = (f"// GENERATED by gen_wide_shaders.py from ../shaders/{name}.hlsl -- do not edit by hand.\n"
              f"// T-2790 spike: the row-widened variant; compile with -D SSLM_WIDE_H=<rows> -I ../shaders.\n")
    return header + text


def main() -> int:
    for name in SITES:
        src = (SRC / f"{name}.hlsl").read_text(encoding="utf-8")
        out = widen(name, src)
        (HERE / f"{name}_wide.hlsl").write_text(out, encoding="utf-8", newline="\n")
    print(f"generated {len(SITES)} widened site shaders")
    return 0


if __name__ == "__main__":
    sys.exit(main())
