"""Emit tests/silu_lut_golden_table.h — the canonical SIL1 sigmoid table (as the converter
emits it: numpy float64 round-half-even) pinned as an in-tree C++ literal.

The S2.4 golden-hash test (test_main.cpp) hashes SiluSigmoidQ15's outputs over a canonical
input set to prove the RUNTIME construction is bit-identical across toolchains/ISAs (and, via
the run-only GPU package, across vendors). The table must be a PINNED input, not regenerated by
std::exp at test time: the shipped runtime reads fixed table bytes from the artifact and never
calls a transcendental, so a libm difference across platforms would be a FALSE determinism break.
Pinning the converter's exact table isolates the golden to the integer runtime path.

Run from tools/:  python gen_silu_lut_golden.py
"""
import pathlib
import sslm_model_writer as w

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent / "tests" / "silu_lut_golden_table.h"


def main():
    t = w.build_sigmoid_lut()
    assert t.size == 1025 and str(t.dtype) == "int32", (t.size, t.dtype)
    lines = [
        "// Auto-generated by tools/gen_silu_lut_golden.py (build_sigmoid_lut, N=1024, X=16, Q15).",
        "// The CANONICAL SIL1 table as the converter emits it (numpy float64 round-half-even).",
        "// Pinned as data so the golden-hash test isolates the RUNTIME construction from libm:",
        "// the runtime reads fixed table bytes, never std::exp, so the golden must too.",
        "#ifndef SUPERSLM_TESTS_SILU_LUT_GOLDEN_TABLE_H",
        "#define SUPERSLM_TESTS_SILU_LUT_GOLDEN_TABLE_H",
        "#include <cstdint>",
        "namespace superslm_test {",
        "inline constexpr int32_t kSiluLutGoldenTable[1025] = {",
    ]
    vals = [str(int(x)) for x in t]
    for i in range(0, len(vals), 16):
        lines.append("\t" + ", ".join(vals[i:i + 16]) + ",")
    lines += ["};", "}  // namespace superslm_test", "#endif"]
    text = "\n".join(lines) + "\n"
    # Pure ASCII, written as UTF-8 with an explicit newline. Both halves are load-bearing
    # for the byte-for-byte reproducibility this pinned table depends on: write_text with no
    # encoding= uses the platform's locale encoding, so a single non-ASCII character would
    # serialize to different bytes on a Windows host (cp1252) than on a Linux one (UTF-8)
    # for an unchanged table, and would raise outright under a C/POSIX locale. Asserting
    # ASCII here means the property cannot lapse by someone adding a typographic character
    # to a comment above. (Same defect and same fix as tools/gen_matmul_golden.py.)
    text.encode("ascii")  # raises UnicodeEncodeError if a non-ASCII character crept in
    OUT.write_text(text, newline="\n", encoding="utf-8")
    print(f"wrote {OUT} (1025 entries; table[0]={t[0]}, table[512]={t[512]}, table[1024]={t[1024]})")


if __name__ == "__main__":
    main()
