"""T-1777 out-of-distribution document set -- original short sentences, not
drawn from the shopkeeper booking domain the pooling scheme (D-SLM447) and
this project's own quantization campaign were calibrated on. Written for this
ticket; no external or copyrighted source. Kept in the same rough length
band as the in-distribution shopkeeper utterances (short, colloquial,
single-turn) so length is not a confound between the two populations.
"""

OOD_DOCUMENTS = [
    "The bus to the north side leaves every twenty minutes on weekdays.",
    "I forgot to water the tomatoes again this week.",
    "Can you turn the thermostat down a couple degrees?",
    "The library closes early on Sundays during the summer.",
    "My laptop keeps overheating when I run more than two browser tabs.",
    "We ran out of coffee filters, so I used a paper towel instead.",
    "The trail up to the ridge was muddy after last night's rain.",
    "She switched her flight to avoid the layover in Denver.",
    "The recipe calls for a pinch of cumin, not a full teaspoon.",
    "Our internet dropped twice during the video call this morning.",
    "The mechanic said the brake pads need replacing before winter.",
    "He's been practicing the same four chords for a month straight.",
    "The bakery on Fifth sells out of sourdough by ten most days.",
    "I need to renew my passport before the trip in the spring.",
    "The printer is jammed again and nobody has the manual.",
    "They repainted the fence a darker shade of green last weekend.",
    "The kids built a fort out of couch cushions in the living room.",
    "Traffic on the bridge was backed up for almost an hour.",
    "The new washing machine is quieter but takes longer per cycle.",
    "I lost my umbrella somewhere between the office and the station.",
    "The garden needs weeding before it gets too hot to work outside.",
    "He switched careers from accounting to woodworking two years ago.",
    "The power went out for about ten minutes during the storm.",
    "She's teaching herself to read sheet music from an old book.",
    "The neighbors are hosting a barbecue this Saturday afternoon.",
    "My phone battery drains fast whenever the screen brightness is high.",
    "The museum added a new wing for contemporary sculpture last year.",
    "We switched grocery stores because the produce lasted longer.",
    "The hiking boots finally broke in after the third trip.",
    "I can't remember if the meeting got moved to Thursday or Friday.",
    "The cat knocked a plant off the windowsill again this morning.",
    "They're repaving the parking lot, so use the side entrance.",
    "The soup needed more salt but the bread turned out great.",
    "His car wouldn't start until he jiggled the battery cable.",
    "The community pool opens for the season next weekend.",
    "I switched to decaf and honestly haven't noticed a difference.",
    "The moving truck was late, so we unpacked well past midnight.",
    "She finally fixed the squeaky hinge on the back door.",
    "The lecture ran long, so the lab session got pushed to Friday.",
    "We planted two new trees along the driveway last fall.",
    "The forecast says rain all weekend, so the picnic got postponed.",
    "He finally beat his old time on the five-kilometer loop.",
    "The dentist recommended a night guard for the teeth grinding.",
    "Our flight got delayed twice before it was cancelled outright.",
    "The spreadsheet formula was off by one column the whole time.",
    "She donated three boxes of old textbooks to the used bookstore.",
    "The paint fumes lingered in the hallway for almost two days.",
    "We took the scenic route and missed the turn for the highway.",
    "The referee added four minutes of stoppage time at the end.",
    "His phone screen cracked when it slipped out of his back pocket.",
    "The soup kitchen needs more volunteers on Tuesday evenings.",
    "They replaced the old boiler right before the cold snap hit.",
    "The article cited a study that nobody could actually locate.",
    "Our team lost the scrimmage but the defense looked much sharper.",
    "The landlord finally fixed the leak under the kitchen sink.",
    "She switched her thesis topic twice before settling on the third.",
    "The ferry only runs twice a day during the off season.",
    "He keeps forgetting to charge his headphones overnight.",
    "The orchestra rehearsal ran an extra hour before the concert.",
    "We compared three quotes before picking a contractor for the roof.",
    "The vending machine ate my dollar and gave nothing back.",
    "Her flight arrives an hour before mine, so we'll wait at the gate.",
    "The recipe swap at work turned up three different lasagna versions.",
    "The construction crew started jackhammering right at seven.",
    "I keep mixing up the two identical office keys on my ring.",
    "The astronomy club meets on the roof whenever the sky is clear.",
    "Our internet provider raised prices again without much notice.",
    "The marathon route was rerouted because of a downed tree.",
    "He replaced the bike chain himself after watching a few videos.",
    "The conference badge printer jammed right before the keynote.",
    "She keeps a spreadsheet of every plant and when it was last watered.",
    "The used car had more mileage than the listing actually said.",
    "Our office moved two floors down after the lease renewal.",
    "The choir added an extra rehearsal before the holiday concert.",
    "He swapped the summer tires for winter ones a bit too late.",
    "The farmers market moves indoors once the weather turns cold.",
    "Her suitcase came off the carousel with a broken wheel.",
    "The new intern mixed up two client folders on the first day.",
    "We ran the dishwasher twice because the first load wasn't dry.",
    "The trail map at the ranger station was three years out of date.",
    "He finally organized the garage after putting it off all spring.",
    "The apartment upstairs plays music loud enough to hear the bass.",
    "Our book club picked a much longer novel than usual this month.",
    "The delivery driver left the package with the wrong neighbor.",
    "She's rewiring the old lamp instead of buying a new one.",
    "The city repaved two blocks but skipped the worst pothole.",
    "His allergy medication makes him drowsy by mid-afternoon.",
    "The spreadsheet crashed right before anyone hit save.",
    "We switched seats twice before the movie finally started.",
    "The community garden plots get assigned by lottery each spring.",
    "Her car passed inspection but just barely on the emissions test.",
    "The office coffee machine only makes decaf on Fridays somehow.",
    "They rescheduled the flight training around the storm system.",
    "The plumber quoted twice what the first estimate said.",
    "Our neighborhood lost power for six hours during the heat wave.",
    "He finally labeled all the boxes in the storage unit.",
    "The subway delay pushed the whole meeting back by twenty minutes.",
    "She switched her running shoes after the old pair wore through.",
    "The greenhouse thermometer reads five degrees warmer than outside.",
]
